spring:
  application:
    name: collector
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      # не загружать другие компоненты, до получения конфигурации
      fail-fast: true
      # если config-server недоступен - делать несколько попыток подключиться
      retry:
        # используем случайный backoff между попытками
        useRandomPolicy: true
        # максимальный интервал в течении которого делаем попытки (6000 миллисекунд = 6 сек)
        max-interval: 6000